### ISSUE TITLE
config problem

### ISSUE THREAD

**Issue by faschinr** [mscharl/MMM-oebb-station-board#1]
hey @mscharl my problem is, it work's not maybe you can show an example how it must in config.js or required fields in description. would nice :) thanks

**Comment by faschinr** [comment]
solve it by my own(I try it with module: "MMM-oebb-station-board"), maybe it helps other if you make an example in readme. 
`module: 'MMM-oebb-station-board'`

**Comment by mscharl** [comment]
Great that you could solve it yourself.
I added an example to the readme as suggested.
